### ISSUE TITLE
BUG: beforeAll() with a page.goto with incorrect URL generates strange error: UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by thernstig** [mmarkelov/jest-playwright#67]
Promise errors in `beforeAll()` gives some un-understandable errors, see below. I could not replicate this with just using Playwright standalone.

**Code**

```javascript
beforeAll(async () => {
  await page.goto(`http://0.0.0.5:8080/`);
});

it('enter password', async () => {
  await page.type('#password', 'test');
});
```

**Output**

```sh
(node:102419) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /home/userA/code/projectA/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
    at new Promise (<anonymous>)
    at CRSession.send (/home/userA/code/projectA/node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
    at CRExecutionContext.evaluate (/home/userA/code/projectA/node_modules/playwright-core/lib/chromium/crExecutionContext.js:69:50)
    at FrameExecutionContext._evaluate (/home/userA/code/projectA/node_modules/playwright-core/lib/dom.js:35:35)
    at FrameExecutionContext.ExecutionContext.evaluateHandle (/home/userA/code/projectA/node_modules/playwright-core/lib/javascript.js:24:25)
    at RerunnableTask._task (/home/userA/code/projectA/node_modules/playwright-core/lib/dom.js:485:24)
    at RerunnableTask.rerun (/home/userA/code/projectA/node_modules/playwright-core/lib/frames.js:836:23)
  -- ASYNC --
    at Frame.<anonymous> (/home/userA/code/projectA/node_modules/playwright-core/lib/helper.js:54:23)
    at Page.type (/home/userA/code/projectA/node_modules/playwright-core/lib/page.js:374:33)
    at Page.type (/home/userA/code/projectA/node_modules/playwright-core/lib/helper.js:55:31)
    at Object.<anonymous> (/home/userA/code/projectA/tests/sample.e2e.test.js:6:14)
    at Object.asyncJestTest (/home/userA/code/projectA/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
    at /home/userA/code/projectA/node_modules/jest-jasmine2/build/queueRunner.js:43:12
    at new Promise (<anonymous>)
    at mapper (/home/userA/code/projectA/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
    at /home/userA/code/projectA/node_modules/jest-jasmine2/build/queueRunner.js:73:41
(node:102419) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:102419) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 FAIL   E2E  tests/sample.e2e.test.js (10.538s)
  ✕ enter password (5003ms)

  ● enter password

    While navigating to http://0.0.0.5:8080/: net::ERR_INVALID_ARGUMENT at http://0.0.0.5:8080/

      1 | beforeAll(async () => {
    > 2 |   await page.goto(`http://0.0.0.5:8080/`);
        |   ^
      3 | });
      4 |
      5 | it('enter password', async () => {

      at throwIfError (../node_modules/playwright-core/lib/frames.js:330:19)
      at Frame.goto (../node_modules/playwright-core/lib/frames.js:307:9)
      at Object.<anonymous> (sample.e2e.test.js:2:3)
        -- ASYNC --
      at Frame.<anonymous> (../node_modules/playwright-core/lib/helper.js:54:23)
      at Page.goto (../node_modules/playwright-core/lib/page.js:224:33)
      at Page.goto (../node_modules/playwright-core/lib/helper.js:55:31)
      at Object.<anonymous> (sample.e2e.test.js:2:14)

  ● enter password

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      3 | });
      4 |
    > 5 | it('enter password', async () => {
        | ^
      6 |   await page.type('#password', 'test');
      7 | });
      8 |

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (sample.e2e.test.js:5:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.836s
Ran all test suites matching /e2e/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

Removing the beforeAll() and instead doing this:

```javascript
it('enter password', async () => {
  await page.goto(`http://0.0.0.5:8080/`);
  await page.type('#password', 'test');
});
```

Instead gives a better error:

```sh
 FAIL   E2E  sample.e2e.test.js (5.565s)
  ✕ enter password (9ms)

  ● enter password

    While navigating to http://0.0.0.5:8080/: net::ERR_INVALID_ARGUMENT at http://0.0.0.5:8080/
```

**Comment by mmarkelov** [comment]
Some research on it. Maybe we should add event listener for this?
```js
        process.on('unhandledRejection', (reason) => {
            console.error(reason.message)
        });
```
I'm not sure that is right decision

**Comment by thernstig** [comment]
I actually now noticed that `While navigating to http://0.0.0.5:8080/: net::ERR_INVALID_ARGUMENT at http://0.0.0.5:8080/` is seen in the first sampe as well, but much further down after the test cases started. So at least the proper error is in there somewhere. But obviously all the obscure errors reported before that is a problem.

It would be interesting to see if this is solved with jest-circus, which looks like it might have better unhandled promise rejections, at least from the little I read up on the topic e.g. here https://github.com/facebook/jest/issues/1852.  Not sure that helps you know though, but maybe it is not worth fixing this if jest-circus is going to be the default in Jest 26, and also since Playwright is in beta.

In we also handle `unhandledRejection` as your proposal in order to hook up a logger (for proper logging functionality). But very few errors should end up there. The proper solution would be to handle it earlier, e.g. directly in beforeAll with a try-catch, but it's most probably users do not though this. So I assume the default catch logic for this would be best in beforeAll, and maybe that is what jest-circus does.

Not sure I helped in any way, but it's always good to add to the discussion.

**Comment by thernstig** [comment]
Oh, and adding an even listener like you suggest would still give that un-understandable output.

I think the main problem is that the having a `page.goto()` error inside `it()` gives a proper error whilst having it in `beforeAll()` does not. Even though the error is exactly the same.

Again maybe this is a problem with Jest, that jest-circus solves? Or maybe it is even a promise with Playright?

**Comment by mxschmitt** [comment]
Will close the issue for now if it's okay. For my understanding the issue comes up if Jest timeout < Playwright timeout. Thats why in the end no verbose error reporting will be generated which line timed out.
ref: https://github.com/mmarkelov/jest-playwright#error-reporting-with-jest
